version: "3.7"

services:
    # image finance
    finance:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: finance
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:1.25.3
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # postgres
    postgres:
        image: postgres:16.1
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-finance}
            POSTGRES_USER: ${DB_USERNAME:-finance}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_SCHEMA: ${DB_SCHEMA:-finance}
        volumes:
            - ./.docker/postgresql:/var/lib/postgresql
        ports:
            - "5432:5432"
        networks:
            - laravel

    # redis
    redis:
        image: redis:7.2.3
        container_name: redis
        restart: unless-stopped
        networks:
            - laravel

    #rede bridge
networks:
    laravel:
        driver: bridge
